name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 构建项目
    - name: Build project
      run: npm run build

    # 部署到 S3
    - name: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1

    - name: Sync using AWS CLI
      run: |
        aws s3 sync static s3://${{ vars.R2_BUCKET }}/static --endpoint-url ${{ vars.R2_ENDPOINT }} --delete --exclude ".*" --checksum-algorithm CRC32 --size-only
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ vars.R2_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.R2_REGION }}
